### PR TITLE
Update script compatibility with Unity6 changes to Rigidbody properties

### LINKED ISSUE #949: [BUG] Script updates needed to be compatible with changes to Rigidbody properties in Unity 6
## Describe the bug

Unity 6 changes certain Rigidbody property names, e.g. velocity to linearVelocity.

## To reproduce

Open feature/XRI3 project in Unity 6, causing auto modification to scripts using no longer valid Rigidbody property names.

## Expected behavior

MRTK3 version 4 scripts ready for Unity 6.

## Your setup (please complete the following information)

- Unity Version [e.g. 6000.0.23f1]
- MRTK Version 4.0.0

## Target platform (please complete the following information)

- HoloLens 2
- Magic Leap
- OpenXR

### PR DESCRIPTION
**Pull request by whebertML**
Fixes #949

### CODE REVIEW

**Review by keveleigh — APPROVED** [review]

**Comment by whebertML** [comment]
@keveleigh Thanks for review earlier, but I had forgotten to update spatialmanipulation package version, now good I think.

**Review by shaynie — APPROVED** [review]

**Pull request merged**
