### PR TITLE
ObjectManipulator's ManipulationLogic observes XRSocketInteractor

### LINKED ISSUE #492: [FEATURE REQUEST] ObjectManipulator observes XRSocketInteractor selection as expected.
When being selected by an XRSocketInteractor, an ObjectManipulator does not move into the socket transform as expected, like an XRGrabInteractable would.  This is due to the default manipulation logic for ObjectManipulator, which is to retain the relative pose offset of an interactor's attach transform.  So when selected by an XRSocketInteractor, the ObjectManipulator stays where it is instead of moving into the socket.

With the intent to increase MRTK3's compatibility with continuing XRI features, the request is to modify ObjectManipulator's behavior so that it properly observes the XRSocketInteraction selection and moves into the socket transform.

Video demonstrating both current and new behavior with the changes from #567 :

https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/58860572/e79cb0fb-60bb-4549-b457-725df993720e

### PR DESCRIPTION
**Pull request by whebertML**
* Modifies ManipulationLogic for position and rotation to properly observe XRSocketInteractor.
* Turns off object smoothing when selected by XRSocketInteractor.
* Also observes XRRayInteractor forceGrab property for position, moving the object to the ray interactor's force grab attach transform.

Resolves #492

### CODE REVIEW

**Review by david-c-kline — DISMISSED** [review]
Approved pending unit test success :smile:

**Review by AMollis — APPROVED** [review]

**Comment by whebertML** [comment]
Unit tests added.

**Review by AMollis — APPROVED** [review]

**Comment by anonymous2585** [comment]
@whebertML thank you for this improvement!

I tested it and it works but the option "Hover Socket Snapping" is not observed by the ObjectManipulator when it is set to `true`: the object don't snap to the socket attach position before user release select.

Can you check if you have the same behaviour and open another issue if confirmed?

**Comment by whebertML** [comment]
@anonymous2585   Thank you for testing the feature!

I believe the MRTK3 project itself is still only dependent on XRI version 2.3.0, which doesn't yet contain the `Hover Socket Snapping` property of `XRSocketInteractor`.  Not sure when that was introduces (XRI 2.5.2?), but such a feature could be added when the project upgrades it's dependency on a newer XRI I would think.

**Comment by anonymous2585** [comment]
@whebertML You are right! I didn't noticed [Hover Socket Snapping was added only in XRI 2.5.0](https://docs.unity3d.com/Packages/com.unity.xr.interaction.toolkit@2.5/changelog/CHANGELOG.html#250---2023-08-17)
> Added snap transformations to XRSocketInteractor on hover.

Yes, we use XRI 2.5.2.

Maybe it's feasible to support it when the installed XRI package is `>= 2.5.0`?

**Comment by whebertML** [comment]
@anonymous2585 Definitely technical possibly of course.  Please feel free to add a feature request and it will be discussed.

**Pull request merged**
